#!/usr/bin/env python3
"""Generate docs/frame_test_vectors.json - shared ground truth for frame math.

Both sides of the Unity bridge convert between ROS/Gazebo (ENU: x=East,
y=North, z=Up, right-handed) and Unity (x=East, y=Up, z=North, left-handed).
Getting that wrong gives a mirrored or rotated world that still "looks fine",
so the expected values are computed here, independently of either
implementation, with plain rotation matrices:

    S = swap(y, z)          ENU vector v  ->  Unity vector S v
    R_unity = S R_enu S     (S is its own inverse; det S = -1 flips handedness)

Sun positions come from pvlib (NREL SPA), a well-tested reference.

The C# EditMode tests (unity/com.guardian.sim/Tests) and the Python bridge
tests both read this file. Regenerate with:
    ~/.venvs/geo/bin/python scripts/make_frame_test_vectors.py
"""

import json
import math
from pathlib import Path

import numpy as np
import pandas as pd
import pvlib
from scipy.spatial.transform import Rotation

S = np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]], float)
OUT = Path(__file__).resolve().parent.parent / "docs" / "frame_test_vectors.json"


def unity_quat(r_enu: Rotation) -> list[float]:
    """ROS/ENU rotation -> Unity quaternion (x, y, z, w), canonical w >= 0."""
    m = S @ r_enu.as_matrix() @ S
    # m has det +1 (S . R . S with det S = -1 twice), so it is a valid rotation
    q = Rotation.from_matrix(m).as_quat()      # x, y, z, w
    return [round(float(v), 9) for v in (q if q[3] >= 0 else -q)]


def main():
    points = [
        {"enu": [1, 0, 0], "unity": [1, 0, 0], "note": "East stays +X"},
        {"enu": [0, 1, 0], "unity": [0, 0, 1], "note": "North becomes +Z"},
        {"enu": [0, 0, 1], "unity": [0, 1, 0], "note": "Up becomes +Y"},
        {"enu": [-12.5, 40.25, 3.0], "unity": [-12.5, 3.0, 40.25], "note": "general point"},
    ]

    # Yaw (CCW from East, ENU) -> Unity Euler Y (degrees, clockwise seen from above).
    #  * objects whose length axis is local +X (fence panels, gates):  y = -yaw
    #  * objects that face local +Z (people, cameras, vehicles):        y = 90 - yaw
    yaws = []
    for deg in (0, 30, 90, -40.2, 180, 270):
        yaw = math.radians(deg)
        yaws.append({"yaw_enu_deg": deg,
                     "unity_euler_y_x_aligned": round(-deg, 6),
                     "unity_euler_y_z_forward": round(90 - deg, 6),
                     "direction_unity": [round(math.cos(yaw), 9), 0.0,
                                         round(math.sin(yaw), 9)]})

    # Full rotations: ROS quaternion (x,y,z,w) -> Unity quaternion (x,y,z,w).
    # Closed form this should equal: (-qx, -qz, -qy, qw).
    rots = []
    for rpy in ((0, 0, 90), (0, 0, -40.2), (10, 0, 0), (0, 30, 0), (10, -20, 135), (-5, 12, 250)):
        r = Rotation.from_euler("xyz", rpy, degrees=True)
        q_ros = r.as_quat()
        rots.append({"ros_rpy_deg": list(rpy),
                     "ros_quat_xyzw": [round(float(v), 9) for v in q_ros],
                     "unity_quat_xyzw": unity_quat(r),
                     "ros_x_axis_in_unity": [round(float(v), 9)
                                            for v in S @ r.apply([1, 0, 0])]})

    # Sun: Bonn Poppelsdorf launch pad, several local times.
    lat, lon = 50.725890272, 7.086701902
    times = pd.DatetimeIndex(["2025-06-20T14:00:00", "2025-06-20T06:00:00",
                              "2025-12-21T12:00:00", "2025-03-20T17:30:00"],
                             tz="Europe/Berlin")
    sp = pvlib.solarposition.get_solarposition(times, lat, lon, altitude=60.85)
    sun = [{"local_time": t.strftime("%Y-%m-%dT%H:%M:%S"), "timezone": "Europe/Berlin",
            "utc": t.tz_convert("UTC").strftime("%Y-%m-%dT%H:%M:%SZ"),
            "lat": lat, "lon": lon,
            "elevation_deg": round(float(row.apparent_elevation), 3),
            "azimuth_deg_from_north_cw": round(float(row.azimuth), 3)}
           for t, row in sp.iterrows()]

    OUT.write_text(json.dumps({
        "description": "Shared frame-conversion and sun-position test values. "
                       "ENU: x=East,y=North,z=Up (right-handed). Unity: x=East,y=Up,"
                       "z=North (left-handed). Generated by scripts/make_frame_test_vectors.py",
        "tolerance": {"position_m": 1e-6, "quaternion": 1e-6, "angle_deg": 1e-6,
                      "sun_deg": 1.0},   # NOAA shortcut is good to ~0.5 deg; shadows need ~1 deg
        "points": points, "yaw": yaws, "rotations": rots, "sun": sun}, indent=1))
    print(f"wrote {OUT}")
    for s in sun:
        print(f"  sun {s['local_time']}: elevation {s['elevation_deg']:.2f}, "
              f"azimuth {s['azimuth_deg_from_north_cw']:.2f}")
    # the closed form Unity code will use must agree with the matrix method
    for r in rots:
        x, y, z, w = r["ros_quat_xyzw"]
        closed = np.array([-x, -z, -y, w]); closed = closed if closed[3] >= 0 else -closed
        assert np.allclose(closed, r["unity_quat_xyzw"], atol=1e-8), r
    print("  closed form (-qx, -qz, -qy, qw) matches the matrix method")


if __name__ == "__main__":
    main()
